var GHPATH = '/mnts.dc.org';
var APP_PREFIX = 'gppwa_';
var VERSION = "0.1.1-09042026";
var URLS = [
  `${GHPATH}/index_data/Scripts/avatars/avatar_ai_loader.js`,
  `${GHPATH}/index_data/Scripts/avatars/avatar_animated_loader.js`,
  `${GHPATH}/index_data/Scripts/avatars/avatar_bound_loader.js`,
  `${GHPATH}/index_data/Scripts/avatars/avatar_mecha_default_loader.js`,
  `${GHPATH}/index_data/Scripts/avatars/avatar_mecha_events_loader.js`,
  `${GHPATH}/index_data/Scripts/avatars/avatar_other_loader.js`,
  `${GHPATH}/index_data/Scripts/avatars/avatar_pilot_default_loader.js`,
  `${GHPATH}/index_data/Scripts/avatars/avatar_pilot_events_loader.js`,
  `${GHPATH}/index_data/Scripts/avatars`,
  `${GHPATH}/index_data/Scripts/errors.js`,
  `${GHPATH}/index_data/Scripts/loads.js`,
  `${GHPATH}/index_data/Scripts/main/open_avatars.js`,
  `${GHPATH}/index_data/Scripts/main/open_stickers.js`,
  `${GHPATH}/index_data/Scripts/main/open_wallpapers.js`,
  `${GHPATH}/index_data/Scripts/main`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_cyrus_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_emoji_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_general_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_iori_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_ivan_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_jaka_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_jiu_chong_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_joanna_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_kikina_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_kizuna_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_lillian_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_mila_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_mobius_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_nighthalk_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_ning_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_norma_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_opal_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_other_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_purity_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_red_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_riko_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_rom_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_serena_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_shin_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_silver_deacon_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_vanessa_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_villar_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_vita_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_yutong_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers/sticker_zoe_loader.js`,
  `${GHPATH}/index_data/Scripts/stickers`,
  `${GHPATH}/index_data/Scripts/variables.js`,
  `${GHPATH}/index_data/Scripts/wallpapers/pagination_tabs.js`,
  `${GHPATH}/index_data/Scripts/wallpapers/paginations_controller.js`,
  `${GHPATH}/index_data/Scripts/wallpapers/wallpapers_ai_loader.js`,
  `${GHPATH}/index_data/Scripts/wallpapers/wallpapers_images_loader.js`,
  `${GHPATH}/index_data/Scripts/wallpapers`,
  `${GHPATH}/index_data/Scripts/windows/copy_gif.js`,
  `${GHPATH}/index_data/Scripts/windows/copy_png.js`,
  `${GHPATH}/index_data/Scripts/windows/copy_vid.js`,
  `${GHPATH}/index_data/Scripts/windows/download_gif.js`,
  `${GHPATH}/index_data/Scripts/windows/download_png.js`,
  `${GHPATH}/index_data/Scripts/windows/download_vid.js`,
  `${GHPATH}/index_data/Scripts/windows/locator.js`,
  `${GHPATH}/index_data/Scripts/windows/preview_gif.js`,
  `${GHPATH}/index_data/Scripts/windows/preview_png.js`,
  `${GHPATH}/index_data/Scripts/windows/preview_vid.js`,
  `${GHPATH}/index_data/Scripts/windows/tabs.js`,
  `${GHPATH}/index_data/Scripts/windows/time.js`,
  `${GHPATH}/index_data/Scripts/windows`,
  `${GHPATH}/index_data/Scripts/wndows_close.js`,
  `${GHPATH}/index_data/Scripts/year.js`,
  `${GHPATH}/index_data/Scripts`,
  `${GHPATH}/index_data/Styles/style.css`,
  `${GHPATH}/index_data/Styles/style_main.css`,
  `${GHPATH}/index_data/Styles/style_windows.css`,
  `${GHPATH}/index_data/Styles`,
  `${GHPATH}/index_data/Textures/close.png`,
  `${GHPATH}/index_data/Textures/copy.png`,
  `${GHPATH}/index_data/Textures/download.png`,
  `${GHPATH}/index_data/Textures/icon_0.png`,
  `${GHPATH}/index_data/Textures/logo.png`,
  `${GHPATH}/index_data/Textures/netease.png`,
  `${GHPATH}/index_data/Textures`,
  `${GHPATH}/index_data`,
  `${GHPATH}/index.html`
];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(VERSION).then(cache => cache.addAll(URLS)));
});
self.addEventListener('fetch', event => {
  event.respondWith(caches.match(event.request).then(response => {
    if (response) {
      return response;
    }
    return fetch(event.request);
    })
  );
});